### PR TITLE
Remove --no-run-if-empty flag on removing branches that are merged to master

### PR DESCRIPTION
**Pull request by kadikraman**
On the tip: **Remove branches that have already been merged with master**
I tried to run the command as it is and got an error
```
xargs: illegal option -- -
```
Running just `git branch --merged master | grep -v '^\*' | xargs -n 1 git branch -d ` worked as it should and running the same command twice (when there are no applicable branches) threw no errors.

### CODE REVIEW

**Comment by Arkansaw** [comment]
Unsubscribe 

SENT FROM OUTER SPACE 🚀 

-----Original Message-----

**Comment by exalted** [comment]
@kadikraman have you tried to run it without `--no-run-if-empty` when you're on the `master` branch and no other branches exist?

Having said that, apparently `--no-run-if-empty` is available only with the GNU version of `xargs`.

**Comment by kadikraman** [comment]
Good shout @exalted I hadn't tried that. Thankfully works fine though :)
screen shot 2016-06-14 at 13 53 51

**Comment by exalted** [comment]
D-Oh! My bad... I am used to run it with capital `D`, so instead if you try `xargs -n 1 git branch -D` it should fail in that case.

**Pull request merged**
