### PR TITLE
Add alternative to update submodules

### PR DESCRIPTION
**Pull request by infertux**

### CODE REVIEW

**Comment by denisbalyko** [comment]
https://yadi.sk/i/PO53JCrYsbPnd :)

**Comment by hemanth** [comment]
@infertux Please rebase.

**Comment by infertux** [comment]
Haha, what a timing @denisbalyko! I rebased it @hemanth.

Now I'm wondering if `git submodule update --init --recursive` is 100% equivalent to `git submodule update --remote`. It looks like it is from the `man` page.

**Comment by hemanth** [comment]
@infertux Yes! 

It's ok to have them as an alternative anyway.

**Pull request merged**
