### PR TITLE
Move to CSON

### PR DESCRIPTION
**Pull request by tomekwi**
Like YAML, but a lot more lightweight

https://github.com/bevry/cson

### CODE REVIEW

**Comment by hemanth** [comment]
@tomekwi Hmm, not really a fan of `cson`, in our case, we shall be avoiding some commas.

**Comment by tomekwi** [comment]
Fair enough. I’m no fan of JSON, YAML or CSON – but I find CSON the least bad of them all :)

**Comment by tomekwi** [comment]
Yeah, `require('cson').parse(readFileSync(__dirname + '/tips.cson'));` is ugly. It shouldn’t be necessary at all to read anything from any file in `.doxie.render.js`. I’m planning to have a go at `doxie --append` tomorrow.

**Comment by tomekwi** [comment]
> That’s why it took as long as 15 minutes by the way :)

This, to be exact: https://github.com/studio-b12/doxie.render/commit/15ba3e5fa5feb332ed1eb0f865f432303857850a

**Comment by hemanth** [comment]
>When a template imports a non-existent file, doxie.render confusingly reports it as if it couldn’t find the template.

Hmm

**Comment by tomekwi** [comment]
Fixed with the next commit

**Comment by hemanth** [comment]
Heh heh, nice :+1:

**Comment by stoeffel** [comment]
I think json is good enough. And I would like to keep the json (or at least add a build step) because it's easier for third party tools to access it (xhr or depend on this).

**Comment by tomekwi** [comment]
Fair enough – closing this then.

**Comment by hemanth** [comment]
:+1:

**Pull request closed without merging**
