### PR TITLE
Add tip to search commit log for given text

### PR DESCRIPTION
**Pull request by munendrasn**

### CODE REVIEW

**Comment by hemanth** [comment]
You may add it as an alternative to [this](https://github.com/git-tips/tips#find-lines-matching-the-pattern-regex-or-string-in-tracked-files).

**Comment by munendrasn** [comment]
Both are different right??
This PR is for searching `git log` not for searching `tracked` files.
Both usage is slightly different and for different purpose

**Comment by hemanth** [comment]
@munendrasn Hmm, true, please fix the merge conflicts.

**Comment by munendrasn** [comment]
Fixed it

**Pull request merged**
