### PR TITLE
tips.json: submodule to latest commit

### PR DESCRIPTION
**Pull request by angelskieglazki**

### CODE REVIEW

**Comment by hemanth** [comment]
Not sure why the readme has other changes apart from the new entry in the `tips.json`

**Comment by angelskieglazki** [comment]
@hemanth I was also embarrassed. But, I just create branch from master in my fork and run "npm install"

best regards

**Comment by angelskieglazki** [comment]
@hemanth  Please see you last merge in master of head-project: "Tips for log, reset and list currently configure remotes #172"
Similar part of what was added with my commit : [Show changes over time for specific file]

best regards

**Comment by hemanth** [comment]
Only [this](https://github.com/git-tips/tips/pull/174/files#diff-b8b4e42057acf8f00d450ba4627d9e7fR516) change should be visible in the md file.

**Comment by angelskieglazki** [comment]
@hemanth I was guided by the instructions described in contributing.md. They appeared there automatically based on the file tips.json. If you look at your master branch, you will see that these lines are in the tips.json file but they are not generated in the README
```
[Show changes over time for specific file](#show-changes-over-time-for-specific-file)
[Reset: preserve uncommitted local changes](#reset-preserve-uncommitted-local-changes)
[List all currently configured remotes](#list-all-currently-configured-remotes)

```

**Comment by hemanth** [comment]
Thank you, sorry for the delay.

**Pull request merged**
