### PR TITLE
Commit all but one file

### PR DESCRIPTION
**Pull request by jpmens**

### CODE REVIEW

**Comment by hemanth** [comment]
@jpmens Looks like you missed `npm install` check [contributing.md](https://github.com/git-tips/tips/blob/master/contributing.md) thanks!

**Comment by jpmens** [comment]
Was hoping I could avoid that ... ;-)
I've done `npm install` now. How do I fix?

**Comment by hemanth** [comment]
Just do a soft reset on HEAD~1 and commit again, it will generate the readme :+1:

**Comment by jpmens** [comment]
I hope this is better?

**Comment by hemanth** [comment]
Yes Sir, thank you.

**Pull request merged**
