### PR TITLE
Add git push --force-with-lease tip

### PR DESCRIPTION
**Pull request by weirdpattern**
Hey I think this is a good tip, allows you to force a push only if your commit does not overwrite someone else's

### CODE REVIEW

**Comment by hemanth** [comment]
Thanks for the PR, but please have a look at [contributing.md](https://github.com/git-tips/tips/blob/master/contributing.md) and make the changes are per it.

**Comment by weirdpattern** [comment]
I followed all steps the first time...  
Did I miss something? Scratching my head trying to figure out what's wrong =)

**Comment by hemanth** [comment]
Ah, my bad, it looks neat, thanks!

**Comment by weirdpattern** [comment]
Cool, nice work with the repo,  it has saved my day in more than one occasion!

**Pull request merged**
