### PR TITLE
Add list command

### PR DESCRIPTION
**Pull request by arrrggghhh**
Hi,

I added a bash command to list git repositories in certain directories.

It doesn't start with git, but I found it useful in my workflow. I thought it might help some people.

Thanks!

### CODE REVIEW

**Comment by arrrggghhh** [comment]
I'm not sure why, commands get wrapped.

**Comment by hemanth** [comment]
Looks fine now?

**Comment by arrrggghhh** [comment]
@hemanth 

It seems dollar signs in the last commands act like they are new line characters.

I tried to escape them with backslash, but pre commit hook says `Unexpected token $ in JSON`.

Currently, merged commands is broken and won't work.

This is what I inserted at the end of `tips.json`:

```json
{
  "title": "List of git repositories in multiple directories.",
  "tip": "find -E /path1 /path2 /path3 \\( -regex '.*/\\.git$' -not -regex '.*/\\..*/\\.git$' \\) -type d -print0 | xargs -0 -I {} dirname {}",
  "alternatives": [
    "find /path1 /path2 /path3 -regextype posix-egrep \\( -regex '.*/\\.git$' -not -regex '.*/\\..*/\\.git$' \\) -type d -print0 | xargs -0 -I {} dirname {}"
  ]
}
```

And this is the generated markdown:

<pre>
## List of git repositories in multiple directories.
```sh
find -E /path1 /path2 /path3 \( -regex '.*/\.git
 -not -regex '.*/\..*/\.git
 \) -type d -print0 | xargs -0 -I {} dirname {}
```


__Alternatives:__
```sh
find /path1 /path2 /path3 -regextype posix-egrep \( -regex '.*/\.git
 -not -regex '.*/\..*/\.git
 \) -type d -print0 | xargs -0 -I {} dirname {}
```
</pre>

Also, this is the commands what I actually intended and confirmed to work:

```bash
# tip
find -E /path1 /path2 /path3 \( -regex '.*/\.git$' -not -regex '.*/\..*/\.git$' \) -type d -print0 | xargs -0 -I {} dirname {}

# alternatives
find /path1 /path2 /path3 -regextype posix-egrep \( -regex '.*/\.git$' -not -regex '.*/\..*/\.git$' \) -type d -print0 | xargs -0 -I {} dirname {}
```

Please take a look at this. Thanks!

**Comment by hemanth** [comment]
I am in a transit now. 

//cc @spacewander got some spare time? 😇

**Comment by spacewander** [comment]
Maybe a bug of doxie?

**Comment by hemanth** [comment]
@spacewander Right, my bad...he was referring to the formatting issue, I was thinking it was something to do with the `find` command.

//cc @tomekwi

**Comment by spacewander** [comment]
@hemanth
Well...Don't mind it! As for the `find` command, we can shorten it from:
```
-regextype posix-egrep \( -regex '.*/\.git$' -not -regex '.*/\..*/\.git$' \) -type d -print0 | xargs -0 -I {} dirname {}
```
to
```
-regextype posix-egrep \( -regex '[^/]*/([^.]*/)*\.git$' \) -type d -exec dirname {} \;
```
Use `-exec` to replace `xargs`, and squash two regexes into one.

**Pull request merged**
